name: Build
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get project code
        uses: actions/checkout@v3
      - name: Install Deps
        run: yarn install
      - name: Build project
        run: yarn build
